US-ASCII for everyone
GFA-spec/GFA-spec pull request #105
Opened 2020-11-19 19:51 UTC by JervenBolleman

2020-11-23 18:26 UTC, sjackman approved these changes

2020-11-23 18:29 UTC, sjackman requested changes
Thank you for this clarification! I've suggested moving the location of the text. The text itself is great.

2020-11-23 18:29 UTC, sjackman commented on GFA1.md
> +The GFA format is a tab-delimited text format for describing a set of sequences and their overlap. The first field of the line identifies the type of the line. Header lines start with `H`. Segment li
```suggestion
The GFA format is a tab-delimited text format for describing a set of sequences and their overlap. The text is encoded in UTF-8 but is not allowed to use a codepoint value higher than 127. The first field of the line identifies the type of the line. Header lines start with `H`. Segment lines start with `S`. Link lines start with `L`. A containment line starts with `C`. A path line starts with `P`.
```

2020-11-23 18:29 UTC, sjackman commented on GFA2.md
> +
Please append this sentence to the paragraph on line 82.

2020-11-23 19:11 UTC, JervenBolleman commented
> Thank you for this clarification! I've suggested moving the location of the text. The text itself is great.

Text is moved.

2020-11-24 19:03 UTC, sjackman approved these changes
Thank you for your first contribution to GFA-spec, Jerven! 🌟

2020-11-24 19:04 UTC, merged